[package]

name = "rust_collection_examples"
version = "0.0.1"
authors = ["Markus Jais <markus.jais@yahoo.de>"]


[dependencies]
itertools = "0.10.0"
rayon = "1.5.0"
im = "15.0.0"
rpds = "0.8.0"
crossbeam = "0.8.0"
crossbeam-channel = "0.5.0"
crossbeam-deque = "0.8.0"
crossbeam-queue = "0.3.1"


